changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
changelogPath: CHANGELOG.md
versionExt: md
envPrefix: CHANGIE_

# Version headers don't have a 'v' prefix,
# and follow a human-readable date format.
versionFormat: '## {{trimPrefix "v" .Version}} - {{.Time.Format "2 Jan 2006"}}'

projectsVersionSeparator: /
projects:
  - label: zap
    key: zap
    changelog: CHANGELOG.md
  - label: exp
    key: exp
    changelog: exp/CHANGELOG.md

kindFormat: '{{.Kind}}:'
kinds:
- label: Breaking changes
  auto: major
- label: Enhancements
  auto: minor
- label: Other improvements
  auto: minor
- label: Bugfixes
  auto: patch

# We use two custom fields:
#
# - PR: Pull requst number
# - Author: Author of the pull request
#
# However, we don't actually configure these
# because doing so will force specifying them
# when someone calls 'changie new'.
#
# We want to auto-populate both fields in the pull request automatically.

# If PR numbers are specified,
# render reference links for them in each change entry.
#
# The footer will include the destinations for each reference link.
changeFormat: '* {{ with .Custom.PR -}}[#{{.}}][]: {{ end }}{{.Body}}'

# The footer include a list of contributors for the release,
# and the other ends of each reference link for each PR.
footerFormat: |-
  {{- $authors := list }}
  {{- $prs := list }}
  {{- range .Changes }}
    {{- with .Custom.Author }}
      {{- $authors = append $authors (trimPrefix "@" . | printf "@%s") }}
    {{- end }}
    {{- with .Custom.PR }}
      {{- $prs = append $prs . }}
    {{- end }}
  {{- end }}

  {{- with ($authors | sortAlpha | uniq) }}
  Thanks to
  {{- if eq (len .) 1 }} {{ first . }}
  {{- else }} {{ initial . | join ", "}}, and {{ last .}}
  {{- end }} for their contributions to this release.
  {{- end }}

  {{- with ($prs | sortAlpha | uniq) }}
  {{ range . }}
  [#{{ . }}]: https://github.com/uber-go/zap/pull/{{ . }}
  {{- end -}}
  {{ end -}}

newlines:
  afterChangelogHeader: 0
  beforeChangelogVersion: 1
  afterVersion: 1
  endOfVersion: 1
